security:
    encoders:
        Sistema\userBundle\Entity\Usuario: {algorithm: sha512, iterations: 10}
#        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main: 
            entity:
                class: Sistema\UserBundle\Entity\Usuario
                property: email
#        in_memory:
#            memory:
#                users:
#                    - { name: user, password: userpass, roles: [ 'ROLE_USER' ] }
#                    - { name: admin, password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        secured_area:
            pattern: ^/
            anonymous: ~
            form_login: ~
            # http_basic:
            #     realm: "Secured Demo Area"
            logout: ~
        # dev:
        #     pattern:  ^/(_(profiler|wdt)|css|images|js)/
        #     security: false

        # login:
        #     pattern:  ^/demo/secured/login$
        #     security: false

        # secured_area:
        #     pattern:    ^/demo/secured/
        #     form_login:
        #         check_path: _security_check
        #         login_path: _demo_login
        #     logout:
        #         path:   _demo_logout
        #         target: _demo
        #     #anonymous: ~
        #     #http_basic:
        #     #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        # #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
