<?php

namespace OFarrel\Bundle\GuiasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CampoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampoRepository extends EntityRepository
{
}
